import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import About from "../components/content/About";
import Education from "../components/content/Education";
import { ColorRing } from "react-loader-spinner";
import { useEffect, useState } from "react";

export default function Home() {
  const [windowSize, setWindowSize] = useState({
    width: 0,
    height: 0,
  });

  const [loader, setLoader] = useState<Boolean>(false);
  useEffect(() => {
    setLoader(true);
    setTimeout(() => {
      setLoader(false);
    }, 2000);
  }, []);

  const [isMobile, setMobile] = useState<Boolean>(false);
  useEffect(() => {
    const handleSize = () => {
      setWindowSize({
        width: window.innerWidth,
        height: window.innerHeight,
      });
    };
    window.addEventListener("resize", handleSize);
    handleSize();
    return () => window.removeEventListener("resize", handleSize);
  }, []);

  useEffect(() => {
    if (windowSize.width < 640) {
      setMobile(true);
    } else {
      setMobile(false);
    }
  }, [windowSize]);

  return (
    <>
      <Head>
        <title>Portfolio Baden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loader ? (
        <div className="w-100 h-screen bg-[#1f1c18] flex justify-center items-center">
          <ColorRing
            visible={true}
            height="80"
            width="80"
            ariaLabel="blocks-loading"
            wrapperStyle={{}}
            wrapperClass="blocks-wrapper"
            colors={["#e15b64", "#e5afa2", "#8963c1", "#8E0E00", "#849b87"]}
          />
        </div>
      ) : (
        <main className="font-poppins h-screen bg-gradient-to-r from-[#1f1c18] to-[#8E0E00] overflow-y-auto overflow-x-hidden">
          {/*truyền props qua navbar*/}
          <Navbar isMobile={isMobile} />
          <About />
          <Education />
        </main>
      )}
    </>
  );
}
